// <auto-generated />
using System;
using DPSService.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DPSService.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200803145015_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DPSService.DB.CalculationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountRating")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<decimal>("AmountOutstanding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CompleteObligationsDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ContractAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreditCredDateMissedpayout")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAccountOpened")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAccountRating")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateGracePeriodDeclined")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateInterestPaymentDue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfLastPayment")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePaymentDue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateofContractTermination")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GracePeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GracePeriodReason")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("GracePeriodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InterestAmountOutstanding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestAmountPastDue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOP")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<decimal>("NextPaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpCredDateNextpayout")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpCredDateOverdue")
                        .HasColumnType("datetime2");

                    b.Property<string>("OpCredSumNextpayout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OpCredSumPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OpCredSumPayout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherAmountOutstanding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherAmountPastDue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PastDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrincipalAmountOutstanding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrincipalAmountPastDue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaCredSumPayout")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CalculationResults");
                });

            modelBuilder.Entity("DPSService.DB.ContractData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ContractClosedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ContractData");
                });

            modelBuilder.Entity("DPSService.DB.GraceContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankingServiceName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("BankingServiceType")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractNumberABS")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("ContractSignedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContractStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GracePeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GracePeriodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GracePeriodStatus")
                        .HasColumnType("bit");

                    b.Property<int>("LoanPeriodDaily")
                        .HasColumnType("int");

                    b.Property<decimal>("LoanRateDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OldDateClosedContract")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PenaltyPzPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PercentPzPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalPzPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TermVariance")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPercentCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPercentPzPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPercentPzPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdateDTTM")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GraceContacts");
                });

            modelBuilder.Entity("DPSService.DB.InterestCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ContractAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContractKind")
                        .HasColumnType("int");

                    b.Property<string>("ContractNumberABS")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("ContractType")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastDayOfMonth")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("InterestCharges");
                });

            modelBuilder.Entity("DPSService.DB.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DPSService.DB.SupplementaryAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractNumberABS")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("GraceEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NewContractEndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SupplementaryAgreements");
                });
#pragma warning restore 612, 618
        }
    }
}
