GET http://localhost:5026/playergames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Imp1bGlvIiwic3ViIjoianVsaW8iLCJqdGkiOiJhOTExMDk0MyIsInJvbGUiOiJhZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjI2NjkxIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNzQiLCJodHRwOi8vbG9jYWxob3N0OjUwMjYiLCJodHRwczovL2xvY2FsaG9zdDo3MTA5Il0sIm5iZiI6MTY3NDkyNDA1OCwiZXhwIjoxNjgyNzAwMDU4LCJpYXQiOjE2NzQ5MjQwNTksImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.Ts5n5kT_d78JC1AYyM3KonF5boD0tvQprkdzFfcQhws

###
GET http://localhost:5026/mygames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBsYXllcjEiLCJzdWIiOiJwbGF5ZXIxIiwianRpIjoiNzA4NmI4ZjAiLCJyb2xlIjoicGxheWVyIiwic3Vic2NyaXB0aW9uIjoiZ29sZCIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjI2NjkxIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNzQiLCJodHRwOi8vbG9jYWxob3N0OjUwMjYiLCJodHRwczovL2xvY2FsaG9zdDo3MTA5Il0sIm5iZiI6MTY3NDkyNTA1MSwiZXhwIjoxNjgyNzAxMDUxLCJpYXQiOjE2NzQ5MjUwNTIsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.zuRw3S7nZVetjzYw-NCgKGC7OlWsSOEApvPEjocRPVU